version: "3"

services:
  scraping_co:
    image: scraping_img_rss
    build:
      context: news-scraping
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - TZ=UTC-3
